### ISSUE TITLE
moquette的参照部分能告知么

### ISSUE THREAD

**Issue by zer0Black** [dempeZheng/ocean#1]
看到许多mqtt部分的代码参照了moquette的实现，能说一说哪些部分是参照的moquette的么？我正在看moquette的源码，想和你的源码对比参考一下

**Comment by zer0Black** [comment]
还有一个问题是，netty自带了mqtt的编码解码实现，请问一下使用netty自带的实现有什么优缺点么？

**Comment by dempeZheng** [comment]
moquette这个里面包含mqtt的完整基于内存&MapDB持久化的发布订阅模型的实现。
netty自带的mqtt编解码应该只有编码解码部分。

项目抄moquette比较多，后期打算扩展里面的存储部分

个人建议先看moquette 写的还是很清晰的，co下来改一下就可以实现自己的发布订阅或者类似IM的业务

**Comment by zer0Black** [comment]
知道了，感谢，很有帮助
